// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavegaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navega() {
    driver.get("http://127.0.0.1:5500/frontend/app/index.html");
    driver.manage().window().setSize(new Dimension(1547, 813));
    assertThat(driver.findElement(By.cssSelector(".novedades__cabecera")).getText(), is("Novedades"));
    driver.findElement(By.linkText("hazte cliente")).click();
    assertThat(driver.findElement(By.cssSelector("label:nth-child(1)")).getText(), is("Código"));
    driver.findElement(By.id("miForm")).click();
    driver.findElement(By.id("customer_id")).sendKeys("-1");
    assertThat(driver.findElement(By.id("customer_idErr")).getText(), is("El valor debe ser superior o igual a 0"));
    driver.findElement(By.id("customer_id")).sendKeys("0");
    driver.findElement(By.id("customer_id")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("kk@kk");
    driver.findElement(By.id("address_id_trabajo")).click();
    driver.findElement(By.id("btnEnviar")).click();
    driver.findElement(By.linkText("tiendas")).click();
    assertEquals(vars.get("id=titulo").toString(), "Lista de tiendas");
    driver.findElement(By.id("btnSend")).click();
  }
}
