get http://localhost:8091/login?name=kk&password=kk

###

post http://localhost:8091/login?name=kk&password=kk
Content-Type: application/json

{
    "name": "admin",
    "password": "kk"
}

###

post http://localhost:8091/login?name=kk&password=kk
Content-Type: application/json

{
    "name": "falla",
    "password": "kk"
}

###

post http://localhost:8080/auth/login
Content-Type: application/json

{
    "name": "admin",
    "password": "kk"
}

###

get http://localhost:8091/seguro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2NDc1MTYxNzQsImV4cCI6MTY0NzUxNjc3NH0.rfRaqK7AtuHeDqIIeArmjfBI6JVlHmx-oHuwQxAg80Wn-1gKq9D1SyDNcl8hSj02_tmcWd8HVq60HHOVKUiRcQ

###

get http://localhost:8091/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2NDY2NjM2NjMsImV4cCI6MTY0NjY2NDI2M30.PKwUx8Dg0srR5HnPT7cbKF0iSXvVllOMkZBRxIZxjbTYDf6kcOv77MTiGDm2BUKUtBubHosIU2JgmRLwujRe2A

###

get http://localhost:8091/secreto
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2NDY2NjM2NjMsImV4cCI6MTY0NjY2NDI2M30.PKwUx8Dg0srR5HnPT7cbKF0iSXvVllOMkZBRxIZxjbTYDf6kcOv77MTiGDm2BUKUtBubHosIU2JgmRLwujRe2A

###
get http://localhost:8001/demos/auth/seguro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImtrIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0NzU0MTAwMCwiZXhwIjoxNjQ3NTQxNjAwfQ.T2BCJcwg9V8QTYfA-Caeas4Cc1KxaDbBb8mH8RI5W9ySNPsXqX4YcxK7uC3NWP_pW4GwFSJncZX-X5gUGVDawg


###
get http://localhost:8001/demos/auth/secreto
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImtrIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0NzU0MTAwMCwiZXhwIjoxNjQ3NTQxNjAwfQ.T2BCJcwg9V8QTYfA-Caeas4Cc1KxaDbBb8mH8RI5W9ySNPsXqX4YcxK7uC3NWP_pW4GwFSJncZX-X5gUGVDawg

